name: Webhook Notify

on:
  push:
    branches: [main, master]

jobs:
  notify-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send commit details to webhook
        run: |
          curl -X POST "https://webhook.site/bebd9100-18be-4178-a303-46e2d059f43a" \
              -H "Content-Type: application/json" \
              -d '{
                "commit_sha": "${{ github.sha }}",
                "commit_message": "${{ github.event.head_commit.message }}",
                "author": "${{ github.event.head_commit.author.name }}",
                "author_email": "${{ github.event.head_commit.author.email }}",
                "repository": "${{ github.repository }}",
                "branch": "${{ github.ref_name }}",
                "timestamp": "${{ github.event.head_commit.timestamp }}",
                "modified_files": ${{ toJson(github.event.head_commit.modified) }},
                "added_files": ${{ toJson(github.event.head_commit.added) }},
                "removed_files": ${{ toJson(github.event.head_commit.removed) }},
                "commit_url": "${{ github.event.head_commit.url }}"
              }'
